test:
  google_api_keys: "371267539229-2gdhhadtd7es1l4uuq1nmh029oer5158.apps.googleusercontent.com"
  google_app_secrets: "X2KrCpjKqOLx_OWNVig2C9Gv"
development:
  google_api_keys: "371267539229-2gdhhadtd7es1l4uuq1nmh029oer5158.apps.googleusercontent.com"
  google_app_secrets: "X2KrCpjKqOLx_OWNVig2C9Gv"
production:
  google_api_keys: "371267539229-2gdhhadtd7es1l4uuq1nmh029oer5158.apps.googleusercontent.com"
  google_app_secrets: "X2KrCpjKqOLx_OWNVig2C9Gv"